[tool.poetry]
name = "DD_SWGOH-Utils"
version = "0.1.8"
description = ""
authors = ["Stas Cartoon <bycs@mail.ru>"]

[tool.poetry.dependencies]
python = "^3.8"
pip = "^20.2.4"
Django = "^3.1.2"
pandas = "^1.1.3"
requests = "^2.24.0"
bs4 = "^0.0.1"
psycopg2-binary = "^2.8.6"
gunicorn = "^20.0.4"

[tool.poetry.dev-dependencies]
Django = "^3.1.2"
pip = "^20.2.4"
pandas = "^1.1.3"
requests = "^2.24.0"
bs4 = "^0.0.1"
gunicorn = "^20.0.4"
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
