[tool.poetry]
name = "DD_SWGOH-Utils"
version = "0.1.0"
description = ""
authors = ["Stas Cartoon <bycs@mail.ru>"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3.1.2"

[tool.poetry.dev-dependencies]
Django = "^3.1.2"
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
